package escolheranimal;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Marcielli
 */
public class Animal extends javax.swing.JInternalFrame implements ActionListener{

    /**
     * Creates new form Animal
     */
    
    private int animal=0;
    
    public Animal() {
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBGEscolherAnimal = new javax.swing.JPanel();
        jButtonGato = new javax.swing.JButton();
        jButtonCachorro = new javax.swing.JButton();
        jButtonCoelho = new javax.swing.JButton();
        jButtonPeixe = new javax.swing.JButton();
        jButtonTartaruga = new javax.swing.JButton();
        jButtonLeao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanelBGEscolherAnimal.setBackground(new java.awt.Color(255, 255, 255));

        jButtonGato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonGato.setForeground(new java.awt.Color(0, 0, 255));
        jButtonGato.setText("Gato");
        jButtonGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGatoActionPerformed(evt);
            }
        });

        jButtonCachorro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCachorro.setForeground(new java.awt.Color(0, 0, 255));
        jButtonCachorro.setText("Cachorro");
        jButtonCachorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCachorroActionPerformed(evt);
            }
        });

        jButtonCoelho.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCoelho.setForeground(new java.awt.Color(0, 0, 255));
        jButtonCoelho.setText("Coelho");
        jButtonCoelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCoelhoActionPerformed(evt);
            }
        });

        jButtonPeixe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPeixe.setForeground(new java.awt.Color(0, 0, 255));
        jButtonPeixe.setText("Peixe");
        jButtonPeixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeixeActionPerformed(evt);
            }
        });

        jButtonTartaruga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonTartaruga.setForeground(new java.awt.Color(0, 0, 255));
        jButtonTartaruga.setText("Tartaruga");
        jButtonTartaruga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTartarugaActionPerformed(evt);
            }
        });

        jButtonLeao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLeao.setForeground(new java.awt.Color(0, 0, 255));
        jButtonLeao.setText("Leão");
        jButtonLeao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escolha um Animal.");

        javax.swing.GroupLayout jPanelBGEscolherAnimalLayout = new javax.swing.GroupLayout(jPanelBGEscolherAnimal);
        jPanelBGEscolherAnimal.setLayout(jPanelBGEscolherAnimalLayout);
        jPanelBGEscolherAnimalLayout.setHorizontalGroup(
            jPanelBGEscolherAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGEscolherAnimalLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanelBGEscolherAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBGEscolherAnimalLayout.createSequentialGroup()
                        .addComponent(jButtonTartaruga, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLeao, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPeixe, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBGEscolherAnimalLayout.createSequentialGroup()
                        .addComponent(jButtonGato, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCoelho, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelBGEscolherAnimalLayout.setVerticalGroup(
            jPanelBGEscolherAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGEscolherAnimalLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanelBGEscolherAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGato, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCoelho, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanelBGEscolherAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTartaruga, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLeao, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPeixe, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBGEscolherAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBGEscolherAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 656, 524);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGatoActionPerformed
        animal = 1;
        System.out.println(""+animal);
        this.dispose();        
        
    }//GEN-LAST:event_jButtonGatoActionPerformed

    private void jButtonCachorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCachorroActionPerformed
        animal = 2;
        System.out.println(""+animal);
        this.dispose();  
    }//GEN-LAST:event_jButtonCachorroActionPerformed

    private void jButtonCoelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCoelhoActionPerformed
        animal = 3;
        System.out.println(""+animal);
        this.dispose();  
    }//GEN-LAST:event_jButtonCoelhoActionPerformed

    private void jButtonTartarugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTartarugaActionPerformed
        animal = 4;
        System.out.println(""+animal);
        this.dispose();  
    }//GEN-LAST:event_jButtonTartarugaActionPerformed

    private void jButtonLeaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeaoActionPerformed
        animal = 5;
        System.out.println(""+animal);
        this.dispose();  
    }//GEN-LAST:event_jButtonLeaoActionPerformed

    private void jButtonPeixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeixeActionPerformed
        animal = 6;
        System.out.println(""+animal);
        this.dispose();  
    }//GEN-LAST:event_jButtonPeixeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCachorro;
    private javax.swing.JButton jButtonCoelho;
    private javax.swing.JButton jButtonGato;
    private javax.swing.JButton jButtonLeao;
    private javax.swing.JButton jButtonPeixe;
    private javax.swing.JButton jButtonTartaruga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelBGEscolherAnimal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e){
    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
